tasks:
  - before: |
      (
        sudo apt update
        sudo apt -y upgrade
        yes | sudo apt install build-essential wget curl binutils make perl libx11-6 libx11-dev zlib1g zlib1g-dev tcsh
      )
    init: bash gitpod-install-mesa.sh
