tasks:
  - before: |
      (
        sudo apt update
        yes | sudo apt install zsh build-essential wget curl binutils make perl libx11-6 libx11-dev zlib1g zlib1g-dev tcsh
        # yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        # wget https://gist.githubusercontent.com/renbaoshuo/93f75878fe29cf9ad48a675abd69ef97/raw/3b4ddd4f190af6c6466e07da0850618a9c208353/codespaces.zsh-theme -O ~/.oh-my-zsh/custom/themes/codespaces.zsh-theme
        DIR="/workspace/software"
        echo "export MESASDK_ROOT=$DIR/mesasdk" >> ~/.bashrc
        echo "source $DIR/mesasdk/bin/mesasdk_init.sh" >> ~/.bashrc
        echo "export MESA_DIR=$DIR/mesa-r15140" >> ~/.bashrc
        echo "export OMP_NUM_THREADS=2" >> ~/.bashrc
        source ~/.bashrc
      )
    init: yes| zsh gitpod-install-mesa.sh
