tasks:
  - before: |
      (
        sudo apt update
        sudo apt -y upgrade
        sudo apt install -y build-essential wget curl binutils make perl libx11-6 libx11-dev zlib1g zlib1g-dev tcsh
      )
#   init: bash install-mesa.sh
